import React, { useState } from "react";
import PokeCard from "@/components/pokecard/PokeCard";
import Head from "next/head";

export default function Home({ pokemon }) {
  const [search, setSearch] = useState("");
  const searcher = (e) => {
    setSearch(e.target.value);
  };

  let results = [];

  if (!search) {
    results = pokemon;
  } else {
    results = pokemon.filter((dato) =>
      dato.name.toLowerCase().includes(search.toLocaleLowerCase())
    );
  }

  return (
    <>
      <Head>
        <title>POKÉMARTO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-white">
        {/* Título y searchbar  */}
        <div className="py-5 sticky top-0 left-0 w-full glass">
          <h1 className="uppercase text-center text-3xl mb-2">pokémarto</h1>
          <div className="w-11/12 max-w-2xl mx-auto">
            <input
              className="bg-black border p-3 w-full"
              placeholder="Buscar pokémon..."
              type="text"
              value={search}
              onChange={searcher}
            />
          </div>
        </div>

        {/* Pokedex  */}
        <section>
          <div className="w-11/12 mx-auto grid gap-3 grid-cols-1 md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">
            {results.map((poke) => (
              <PokeCard key={poke.id} pokemon={poke} />
            ))}
          </div>
        </section>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch(`https://pokeapi.co/api/v2/pokemon?limit=150`);
  const data = await res.json();

  data.results.forEach((item, index) => {
    item.id = index + 1;
  });

  return {
    props: { pokemon: data.results },
  };
}
