import React from "react";
import PokeCard from "@/components/pokecard/PokeCard";
import Head from "next/head";

export default function Home({ pokemon }) {
  {
    console.log(pokemon);
  }
  const [counter, setCounter] = React.useState(1);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">
            {pokemon.map((poke, index) => (
              <div key={index}>
                <PokeCard nombre={poke.name} img={poke.image} />
              </div>
            ))}
          </div>
        </section>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch(`https://pokeapi.co/api/v2/pokemon?limit=150`);
  const { results } = await res.json();

  const pokemon = results.map((result, index) => {
    const paddedIndex = ("" + (index + 1)).slice(-3);
    const image = `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/${paddedIndex}.svg`;
    return {
      ...result,
      image,
    };
  });

  return {
    props: { pokemon },
  };
}
